int trigPin=13;                                                                                 //triggerpin connected to pin 11
int echoPin=11;                                                                                 //echo pin connected to pin 11
float pingTime;                                                                                   //time taken by ping to hit and return
float speedOfSound;
int targetDist=6;                                                                             //Distance of the target from the sensor
 
void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);                                                                           //Start the serial monitor
  pinMode(trigPin,OUTPUT);                                                                       //Set trigpin for input
  pinMode(echoPin,INPUT);                                                                      //Set echopin for output

}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(trigPin,LOW);
  delayMicroseconds(2000);                                                                      //Give pulse a 2ms for LOW
  digitalWrite(trigPin,HIGH);                                                                   //Generates the ping
  delayMicroseconds(10);                                                                        //pulse high for 10 micro sec
  digitalWrite(trigPin,LOW);                                                                    //ping ___--___ generated by arduino

  pingTime=pulseIn(echoPin,HIGH);                                                               //Looks for the time of a high pulse
  speedOfSound=((targetDist*2)/pingTime)*25400. ;                                               //originally gives speed of sound in inches/microseconds;
  Serial.print("Speed of sound is ");
  Serial.print(speedOfSound);
  Serial.println(" meters/second");                                                             //prints speed of sound in miles/hr
  delay(1000);
  
}
